# Autogenerated wrapper script for GlibNetworking_jll for i686-w64-mingw32
export libgioenvironmentproxy, libgioopenssl

using OpenSSL_jll
using Glib_jll
JLLWrappers.@generate_wrapper_header("GlibNetworking")
JLLWrappers.@declare_file_product(libgioenvironmentproxy)
JLLWrappers.@declare_file_product(libgioopenssl)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, Glib_jll)
    JLLWrappers.@init_file_product(
        libgioenvironmentproxy,
        "bin\\libgioenvironmentproxy.dll",
    )

    JLLWrappers.@init_file_product(
        libgioopenssl,
        "bin\\libgioopenssl.dll",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
